openapi: '3.0.2'
info:
  title: PokemonAPI
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /pokemons/{id}:
    get:
      description: "Get a pokemon by ID"
      parameters: 
        - name: "id"
          in: "path"
          schema:
            type: string
          description: Numeric ID of the user to get
          required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  id:
                    type: "string"
                  name:
                    type: "string"
                  type:
                    type: "string"
                  comment:
                    type: "string"
      operationId: get-pokemon-by-id